; QOH99 Launcher distribution defaults - cnc-ddraw v7.1.0.0
[ddraw]
windowed=true
fullscreen=true
border=false
maintas=true
width=0
height=0
posX=-32000
posY=-32000
renderer=auto
nonexclusive=true
toggle_borderless=true
savesettings=0
shader=Nearest neighbor
d3d9_filter=0
maxfps=-1
maxgameticks=0
